name: medcall
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4

  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  get: ^4.6.6
  iconsax: ^0.0.8
  firebase_core: ^3.9.0
  flutter_svg: ^2.0.16
  flutter_multi_formatter: ^2.13.0
  url_launcher: ^6.3.1
  intl: ^0.20.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5

flutter_launcher_icons:
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  assets:
    - assets/
    - assets/svg/
    - assets/on_boarding/
  uses-material-design: true
